// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ulrigywayovxuyiktnlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscmlneXdheW92eHV5aWt0bmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NDA5NzcsImV4cCI6MjA5MTQxNjk3N30._rf_5EQ69yPVBeXtlJs-56Nd3y3zpUsdu-L9TDM_un0";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);